---
- hosts: nodes
  become: yes
  become_user: jenkins
  tasks:
    - name: stop docker
      service: name=docker state=stopped
      ignore_errors: yes

    - name: Unmount a mounted volume
      mount:
        path: /var/lib/docker
        state: unmounted

    - name: Remove the logical volume.
      lvol:
        vg: vg_docker
        lv: lv_docker
        state: absent
        force: yes
    
    - name: Create a volume group on top of /dev/sdb with physical extent size = 128KiB
      lvg:
        vg: vg_docker
        state: absent
        force: yes
    
    - name: Create a volume group on top of /dev/sdb with physical extent size = 128KiB
      lvg:
        vg: vg_docker
        pvs: /dev/sdb
        pesize: 128K  
    
    
    - name: Create a logical volume 
      lvol:
        vg: vg_docker
        thinpool: rhel-docker-pool
        size: 100%FREE
        
    - name: Create a xfs filesystem on /dev/sdb1
      filesystem:
        fstype: xfs
        dev: /dev/mapper/vg_docker-rhel--docker--pool

    - name: Mount up device by label
      mount:
        path: /var/lib/docker
        src:  /dev/mapper/vg_docker-rhel--docker--pool
        fstype: xfs
        state: present
    
    
    - name: remove any existing docker-storage config file
      file:
        path: /etc/sysconfig/docker-storage
        state: absent
    
    - block:
        - name: create the docker-storage-setup overlayfs config file
          template:
            src: "/var/lib/jenkins/mytest-secrets/docker-storage-setup-dm"
            dest: /etc/sysconfig/docker-storage-setup
            owner: root
            group: root
            mode: 0644
      when:
        - ansible_distribution == "CentOS"

    - name: Install Docker
      package: name=docker state=present

    
    - name: start docker
      service: name=docker state=restarted enabled=true
